name: datastore_hive
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"


dependencies:
  cupertino_icons: ^1.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  rename: ^2.0.1
  url_launcher: ^6.0.20
  eva_icons_flutter: ^3.1.0
  font_awesome_flutter: ^10.2.1


  flutter:
    sdk: flutter

 
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter_icons:
  android: true
  ios: true
  image_path: "assets/free.png"
  adaptive_icon_background: "ffffff"


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic

